# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170823_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='users.User'),
        ),
    ]
