# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='users/img/profile.jpg', upload_to='users'),
        ),
    ]
