# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170825_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default="{%static 'users/img/profile.jpg'%}", upload_to='users'),
        ),
    ]
