# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='prifile_img',
            field=models.ImageField(default='users/profile.jpg', upload_to='users'),
        ),
    ]
