# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170825_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='prifile_img',
            new_name='profile_img',
        ),
    ]
