# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170825_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_url',
            field=models.CharField(default='users//img/profile.jpg', max_length=255),
        ),
    ]
