# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170825_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='users/profile.jpg', upload_to='users'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_url',
            field=models.CharField(default='users/img/profile.jpg', max_length=255),
        ),
    ]
