# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards_created', to='users.User')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='boards_liked', to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='pins', verbose_name='jpg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins_created', to='users.User')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='pins_liked', to='users.User')),
                ('saved_by', models.ManyToManyField(blank=True, related_name='pins_saved', to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='BoardComment',
            fields=[
                ('basecomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pinterest.BaseComment')),
            ],
            bases=('pinterest.basecomment',),
        ),
        migrations.CreateModel(
            name='PinComment',
            fields=[
                ('basecomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pinterest.BaseComment')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest.Pin')),
            ],
            bases=('pinterest.basecomment',),
        ),
        migrations.AddField(
            model_name='board',
            name='pins',
            field=models.ManyToManyField(to='pinterest.Pin'),
        ),
        migrations.AddField(
            model_name='board',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='boards_saved', to='users.User'),
        ),
        migrations.AddField(
            model_name='basecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='boardcomment',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest.Board'),
        ),
    ]
