# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0002_auto_20170823_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
