# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0002_auto_20170823_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='topic',
            field=models.CharField(default='random_topic', max_length=255),
            preserve_default=False,
        ),
    ]
