# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0003_auto_20170823_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.User'),
        ),
        migrations.AlterField(
            model_name='board',
            name='pins',
            field=models.ManyToManyField(related_name='boards', to='pinterest.Pin'),
        ),
    ]
