# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0004_auto_20170823_2130'),
        ('pinterest', '0003_pin_topic'),
    ]

    operations = [
    ]
