# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0006_auto_20170824_1216'),
        ('pinterest', '0005_merge_20170824_1443'),
    ]

    operations = [
    ]
