# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0007_merge_20170824_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pin',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='pins', to='pinterest.Topic'),
        ),
    ]
