# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0008_auto_20170824_1818'),
        ('pinterest', '0007_merge_20170824_1435'),
    ]

    operations = [
    ]
